### ISSUE TITLE
Can I use it for .NET 6.0

### ISSUE THREAD

**Issue by zydjohnHotmail** [CheshireCaat/BASRemote.NET#16]
Hello:
A few days ago, I found that Microsoft has stopped support for .NET 5.0; so it is time to migrate to .NET 6.0.
Let me know if I can use your repo in .NET 6.0 project, I want to use it in a Winforms App.
By the way, can I use it just as Selenium to control browser, and I want to use the repo to control Chrome browser via proxy, is it possible?
Thanks,

**Comment by CheshireCaat** [comment]
> By the way, can I use it just as Selenium to control browser, and I want to use the repo to control Chrome browser via proxy, is it possible?

No, it's not possible.

> Let me know if I can use your repo in .NET 6.0 project, I want to use it in a Winforms App.

I think it won't be compatible with **.NET 5** or **.NET 6** because this library is written using **.NET Framework**. To add such feature, we need to rewrite the entire package, at least up to **.NET Standard**. There are no such plans right now. Feel free to open `PR` for this.
